# Generated by Django 6.0.7 on 2026-08-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_teacher_student_courses_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
